---
deployment:
  tasks:
    - export FRONTEND_SRC=frontend
    - export FRONTEND_BUILD_DIR=dist
    - export FRONTEND_DEPLOY_PATH=/home/abdikoue/abbabiyo.abdiko.com

    # Build frontend
    - cd $FRONTEND_SRC
    - npm install
    - npm run build

    # Ensure deploy path exists
    - mkdir -p $FRONTEND_DEPLOY_PATH

    # Copy build output to public_html (domain root)
    - /bin/cp -R $FRONTEND_BUILD_DIR/* $FRONTEND_DEPLOY_PATH
