const ethiopianRegions = [{ label: "Oromia", value: "Oromia" }];

export const ethiopianZones = {
  Oromia: [
    // Oromia Region
    { label: "Arsi", value: "Arsi" },
    { label: "Bale", value: "Bale" },
    { label: "East Hararghe", value: "East Hararghe" },
    { label: "West Hararghe", value: "West Hararghe" },
    { label: "North Shewa", value: "North Shewa" },
    { label: "South West Shewa", value: "South West Shewa" },
    { label: "West Arsi", value: "West Arsi" },
    { label: "West Guji", value: "West Guji" },
    { label: "East Welega", value: "East Welega" },
    { label: "West Welega", value: "West Welega" },
    { label: "Horro Guduru Welega", value: "Horro Guduru Welega" },
    { label: "Jimma", value: "Jimma" },
    { label: "Illubabor", value: "Illubabor" },
    { label: "Buno Bedele", value: "Buno Bedele" },
    { label: "Guji", value: "Guji" },
    { label: "Kellem Welega", value: "Kellem Welega" },
  ],
};
export const ethiopianWoredas = {
  Arsi: [
    { label: "Aminya", value: "Aminya" },
    { label: "Aseko", value: "Aseko" },
    { label: "Asella Town", value: "Asella Town" },
    { label: "Bale Gasegar", value: "Bale Gasegar" },
    { label: "Batu Dugda", value: "Batu Dugda" },
    { label: "Chole", value: "Chole" },
    { label: "Digeluna Tijo", value: "Digeluna Tijo" },
    { label: "Diksis", value: "Diksis" },
    { label: "Dodota", value: "Dodota" },
    { label: "Enkelo Wabe", value: "Enkelo Wabe" },
    { label: "Gololcha", value: "Gololcha" },
    { label: "Guna", value: "Guna" },
    { label: "Hitosa", value: "Hitosa" },
    { label: "Jeju", value: "Jeju" },
    { label: "Limuna Bilbilo", value: "Limuna Bilbilo" },
    { label: "Lude Hitosa", value: "Lude Hitosa" },
    { label: "Merti", value: "Merti" },
    { label: "Munesa", value: "Munesa" },
    { label: "Robe", value: "Robe" },
    { label: "Seru", value: "Seru" },
    { label: "Sire", value: "Sire" },
    { label: "Sherka", value: "Sherka" },
    { label: "Sude", value: "Sude" },
    { label: "Tena", value: "Tena" },
    { label: "Tiyo", value: "Tiyo" },
  ],
  Bale: [
    { label: "Agarfa", value: "Agarfa" },
    { label: "Robe Town", value: "Robe Town" },
    { label: "Berbere", value: "Berbere" },
    { label: "Dawe Kachen", value: "Dawe Kachen" },
    { label: "Dawe Serara", value: "Dawe Serara" },
    { label: "Delo Menna", value: "Delo Menna" },
    { label: "Dinsho", value: "Dinsho" },
    { label: "Gasera", value: "Gasera" },
    { label: "Ginir", value: "Ginir" },
    { label: "Goba", value: "Goba" },
    { label: "Goba Town", value: "Goba Town" },
    { label: "Gololcha", value: "Gololcha" },
    { label: "Goro", value: "Goro" },
    { label: "Guradamole", value: "Guradamole" },
    { label: "Legehida", value: "Legehida" },
    { label: "Raytu", value: "Raytu" },
    { label: "Seweyna", value: "Seweyna" },
    { label: "Sinana", value: "Sinana" },
  ],
  "East Hararghe": [
    { label: "Babile", value: "Babile" },
    { label: "Badeno", value: "Badeno" },
    { label: "Chinaksen", value: "Chinaksen" },
    { label: "Dadar", value: "Dadar" },
    { label: "Fedis", value: "Fedis" },
    { label: "Girawa", value: "Girawa" },
    { label: "Gola Oda", value: "Gola Oda" },
    { label: "Goro Gutu", value: "Goro Gutu" },
    { label: "Gursum", value: "Gursum" },
    { label: "Haro Maya", value: "Haro Maya" },
    { label: "Jarso", value: "Jarso" },
    { label: "Kersa", value: "Kersa" },
    { label: "Kombolcha", value: "Kombolcha" },
    { label: "Kurfa Chele", value: "Kurfa Chele" },
    { label: "Malka Balo", value: "Malka Balo" },
    { label: "Meyumuluke", value: "Meyumuluke" },
    { label: "Meta", value: "Meta" },
    { label: "Midega Tola", value: "Midega Tola" },
  ],
  "West Hararghe": [
    { label: "Badessa Town", value: "Badessa Town" },
    { label: "Boke", value: "Boke" },
    { label: "Char", value: "Char" },
    { label: "Chiro Town", value: "Chiro Town" },
    { label: "Daru labu", value: "Daru labu" },
    { label: "Doba", value: "Doba" },
    { label: "Gamachis", value: "Gamachis" },
    { label: "Guba Koricha", value: "Guba Koricha" },
    { label: "Habro", value: "Habro" },
    { label: "Kuni", value: "Kuni" },
    { label: "Masela", value: "Masela" },
    { label: "Mieso", value: "Mieso" },
    { label: "Nannawa", value: "Nannawa" },
    { label: "Chiro", value: "Chiro" },
    { label: "Tulo", value: "Tulo" },
  ],
  Borena: [
    { label: "Arero", value: "Arero" },
    { label: "Dillo", value: "Dillo" },
    { label: "Dire", value: "Dire" },
    { label: "Gomole", value: "Gomole" },
    { label: "Miyu", value: "Miyu" },
    { label: "Moyale", value: "Moyale" },
    { label: "Teltele", value: "Teltele" },
    { label: "Yabelo", value: "Yabelo" },
  ],
  "Buno Bedele": [
    { label: "Bedele Zuria", value: "Bedele Zuria" },
    { label: "Bedele Town", value: "Bedele Town" },
    { label: "Borecha", value: "Borecha" },
    { label: "Chewaka", value: "Chewaka" },
    { label: "Chora", value: "Chora" },
    { label: "Dabo Hana", value: "Dabo Hana" },
    { label: "Dega", value: "Dega" },
    { label: "Didessa", value: "Didessa" },
    { label: "Gechi", value: "Gechi" },
    { label: "Mako", value: "Mako" },
  ],
  "East Borana": [
    { label: "Guji woreda", value: "Guji woreda" },
    { label: "Gumi Eldalo", value: "Gumi Eldalo" },
    { label: "Harena Buluk", value: "Harena Buluk" },
    { label: "Liben", value: "Liben" },
    { label: "Meda Welabu", value: "Meda Welabu" },
    { label: "Moyale", value: "Moyale" },
    { label: "Moyale woreda", value: "Moyale woreda" },
    { label: "Negele Borana", value: "Negele Borana" },
    { label: "Oborso", value: "Oborso" },
    { label: "Wachile", value: "Wachile" },
  ],
  "East Shewa": [
    { label: "Ada'a", value: "Ada'a" },
    {
      label: "Adami Tullu and Jido Kombolcha",
      value: "Adami Tullu and Jido Kombolcha",
    },
    { label: "Batu town", value: "Batu town" },
    { label: "Bishoftu", value: "Bishoftu" },
    { label: "Bora", value: "Bora" },
    { label: "Boset", value: "Boset" },
    { label: "Dugda", value: "Dugda" },
    { label: "Fentale", value: "Fentale" },
    { label: "Gimbichu", value: "Gimbichu" },
    { label: "Liben", value: "Liben" },
    { label: "Lome", value: "Lome" },
    { label: "Nannawa", value: "Nannawa" },
    { label: "Adama", value: "Adama" },
  ],
  "East Welega": [
    { label: "Bonaya Boshe", value: "Bonaya Boshe" },
    { label: "Diga", value: "Diga" },
    { label: "Gida Kiremu", value: "Gida Kiremu" },
    { label: "Gobu Seyo", value: "Gobu Seyo" },
    { label: "Gudeya Bila", value: "Gudeya Bila" },
    { label: "Guto Gida", value: "Guto Gida" },
    { label: "Haro Limmu", value: "Haro Limmu" },
    { label: "Ibantu", value: "Ibantu" },
    { label: "Jimma Arjo", value: "Jimma Arjo" },
    { label: "Leka Dulecha", value: "Leka Dulecha" },
    { label: "Limmu", value: "Limmu" },
    { label: "Nekemte", value: "Nekemte" },
    { label: "Nunu Kumba", value: "Nunu Kumba" },
    { label: "Sasiga", value: "Sasiga" },
    { label: "Sibu Sire", value: "Sibu Sire" },
    { label: "Wama Hagalo", value: "Wama Hagalo" },
    { label: "Wayu Tuka", value: "Wayu Tuka" },
  ],
  Guji: [
    { label: "Adola", value: "Adola" },
    { label: "Adola Town", value: "Adola Town" },
    { label: "Ana Sora", value: "Ana Sora" },
    { label: "Bore", value: "Bore" },
    { label: "Dima", value: "Dima" },
    { label: "Girja", value: "Girja" },
    { label: "Harenfema", value: "Harenfema" },
    { label: "Odo Shakiso", value: "Odo Shakiso" },
    { label: "Uraga", value: "Uraga" },
    { label: "Wadera", value: "Wadera" },
  ],
  Illubabor: [
    { label: "Ale", value: "Ale" },
    { label: "Alge Sache", value: "Alge Sache" },
    { label: "Bicho", value: "Bicho" },
    { label: "Bilo Nopha", value: "Bilo Nopha" },
    { label: "Bure", value: "Bure" },
    { label: "Darimu", value: "Darimu" },
    { label: "Didu", value: "Didu" },
    { label: "Doreni", value: "Doreni" },
    { label: "Huka", value: "Huka" },
    { label: "Halu", value: "Halu" },
    { label: "Hurumu", value: "Hurumu" },
    { label: "Metu Zuria", value: "Metu Zuria" },
    { label: "Metu Town", value: "Metu Town" },
    { label: "Nono Sele", value: "Nono Sele" },
    { label: "Supena Sodo", value: "Supena Sodo" },
    { label: "Yayu", value: "Yayu" },
  ],
  Jimma: [
    { label: "Agaro Town", value: "Agaro Town" },
    { label: "Chora Botor", value: "Chora Botor" },
    { label: "Dedo", value: "Dedo" },
    { label: "Gera", value: "Gera" },
    { label: "Gomma", value: "Gomma" },
    { label: "Guma", value: "Guma" },
    { label: "Kersa", value: "Kersa" },
    { label: "Limmu Sakka", value: "Limmu Sakka" },
    { label: "Limmu Kosa", value: "Limmu Kosa" },
    { label: "Mana", value: "Mana" },
    { label: "Omo Nada", value: "Omo Nada" },
    { label: "Seka Chekorsa", value: "Seka Chekorsa" },
    { label: "Setema", value: "Setema" },
    { label: "Shebe Senbo", value: "Shebe Senbo" },
    { label: "Sigmo", value: "Sigmo" },
    { label: "Sokoru", value: "Sokoru" },
    { label: "Tiro Afeta", value: "Tiro Afeta" },
  ],
  "Kelem Welega": [
    { label: "Dale Wabera", value: "Dale Wabera" },
    { label: "Gidami", value: "Gidami" },
    { label: "Hawa Gelan", value: "Hawa Gelan" },
    { label: "Jimma Horo", value: "Jimma Horo" },
    { label: "Mendi", value: "Mendi" },
    { label: "Macha", value: "Macha" },
    { label: "Seyo", value: "Seyo" },
    { label: "Yamalogi Welele", value: "Yamalogi Welele" },
    { label: "Begi", value: "Begi" },
    { label: "Ayira", value: "Ayira" },
    { label: "Anfilo", value: "Anfilo" },
  ],

  "West Guji": [
    { label: "Abaya", value: "Abaya" },
    { label: "Birbirsa Kojowa", value: "Birbirsa Kojowa" },
    { label: "Bule Hora", value: "Bule Hora" },
    { label: "Bule Hora woreda", value: "Bule Hora woreda" },
    { label: "Dugda Dawa", value: "Dugda Dawa" },
    { label: "Hambela Wamena", value: "Hambela Wamena" },
    { label: "Kercha", value: "Kercha" },
    { label: "Gelana", value: "Gelana" },
    { label: "Malka Soda", value: "Malka Soda" },
    { label: "Suro Barguda", value: "Suro Barguda" },
  ],
  "West Welega": [
    { label: "Ayra", value: "Ayra" },
    { label: "Babo Gambela", value: "Babo Gambela" },
    { label: "Begi", value: "Begi" },
    { label: "Boji Chokorsa", value: "Boji Chokorsa" },
    { label: "Boji Dirmaji", value: "Boji Dirmaji" },
    { label: "Genji", value: "Genji" },
    { label: "Gimbi", value: "Gimbi" },
    { label: "Gimbi Town", value: "Gimbi Town" },
    { label: "Guliso", value: "Guliso" },
    { label: "Haru", value: "Haru" },
    { label: "Homa", value: "Homa" },
    { label: "Jarso", value: "Jarso" },
    { label: "Kondala", value: "Kondala" },
    { label: "Kiltu Kara", value: "Kiltu Kara" },
    { label: "Lalo Asabi", value: "Lalo Asabi" },
    { label: "Mana Sibu", value: "Mana Sibu" },
    { label: "Nejo", value: "Nejo" },
    { label: "Nole Kaba", value: "Nole Kaba" },
    { label: "Sayo Nole", value: "Sayo Nole" },
    { label: "Yubdo", value: "Yubdo" },
  ],
  "Oromia Special Zone Surrounding Finfinne": [
    { label: "Akaki", value: "Akaki" },
    { label: "Bereh", value: "Bereh" },
    { label: "Burayu Town", value: "Burayu Town" },
    { label: "Holeta Town", value: "Holeta Town" },
    { label: "Koye Feche", value: "Koye Feche" },
    { label: "Mulo", value: "Mulo" },
    { label: "Sebeta Hawas", value: "Sebeta Hawas" },
    { label: "Sendafa Town", value: "Sendafa Town" },
    { label: "Sululta", value: "Sululta" },
    { label: "Walmara", value: "Walmara" },
  ],
  "South West Shewa": [
    { label: "Ameya", value: "Ameya" },
    { label: "Dano", value: "Dano" },
    { label: "Gudayya", value: "Gudayya" },
    { label: "Masha", value: "Masha" },
    { label: "Shashamene", value: "Shashamene" },
    { label: "Tiya", value: "Tiya" },
    { label: "Wenchi", value: "Wenchi" },
    { label: "Diksis", value: "Diksis" },
    { label: "Kersa", value: "Kersa" },
    { label: "Sebeta", value: "Sebeta" },
  ],

  "West Arsi": [
    { label: "Adaba", value: "Adaba" },
    { label: "Arsi Negele", value: "Arsi Negele" },
    { label: "Dodola", value: "Dodola" },
    { label: "Gedeb", value: "Gedeb" },
    { label: "Asasa", value: "Asasa" },
    { label: "Kofele", value: "Kofele" },
    { label: "Kokosa", value: "Kokosa" },
    { label: "Kore", value: "Kore" },
    { label: "Naannawa", value: "Naannawa" },
    { label: "Shashamane", value: "Shashamane" },
    { label: "Nensebo", value: "Nensebo" },
    { label: "Seraro", value: "Seraro" },
    { label: "Shala", value: "Shala" },
    { label: "Shashamane Town", value: "Shashamane Town" },
  ],
  "North Shewa": [
    { label: "Alego", value: "Alego" },
    { label: "Biyo", value: "Biyo" },
    { label: "Debre Berhan", value: "Debre Berhan" },
    { label: "Debre Sina", value: "Debre Sina" },
    { label: "Ejerie", value: "Ejerie" },
    { label: "Mida", value: "Mida" },
    { label: "Semen Ber", value: "Semen Ber" },
    { label: "Shewa Robit", value: "Shewa Robit" },
    { label: "Shenberet", value: "Shenberet" },
    { label: "Zenabo", value: "Zenabo" },
  ],

  "Horro Guduru Welega": [
    { label: "Abay Chomen", value: "Abay Chomen" },
    { label: "Amuru", value: "Amuru" },
    { label: "Hababo Guduru", value: "Hababo Guduru" },
    { label: "Horro", value: "Horro" },
    { label: "Jardega Jarte", value: "Jardega Jarte" },
    { label: "Jimma Rare", value: "Jimma Rare" },
    { label: "Shambu Town", value: "Shambu Town" },
    { label: "Guduru", value: "Guduru" },
    { label: "Abay Chomen Town", value: "Abay Chomen Town" },
    { label: "Yubdo", value: "Yubdo" },
  ],
};

export default ethiopianRegions;
